-- Create reviews table
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES public.restaurants(id) ON DELETE CASCADE NOT NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    customer_name TEXT,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Reviews are viewable by everyone" 
ON public.reviews FOR SELECT 
USING (true);

-- Allow inserting reviews (in a real app, this should be restricted to the customer who made the order)
CREATE POLICY "Anyone can insert reviews" 
ON public.reviews FOR INSERT 
WITH CHECK (true);

-- Create a function to easily get the average rating and count
CREATE OR REPLACE FUNCTION get_restaurant_rating(rest_id BIGINT)
RETURNS TABLE (
  avg_rating NUMERIC,
  review_count BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COALESCE(ROUND(AVG(rating)::numeric, 1), 0.0) as avg_rating,
    COUNT(*) as review_count
  FROM public.reviews
  WHERE restaurant_id = rest_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Insert some mock reviews for testing so we have data right away
INSERT INTO public.reviews (restaurant_id, customer_name, rating, comment)
SELECT id, 'Customer A', 5, 'อร่อยมากเลยครับ' FROM public.restaurants WHERE id = 1;

INSERT INTO public.reviews (restaurant_id, customer_name, rating, comment)
SELECT id, 'Customer B', 4, 'รสชาติดี แต่อาหารช้าไปนิด' FROM public.restaurants WHERE id = 1;

INSERT INTO public.reviews (restaurant_id, customer_name, rating, comment)
SELECT id, 'Customer C', 5, 'กะเพราอร่อยที่สุดเลย' FROM public.restaurants WHERE id = 1;
